apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82061375-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  # 사번으로 변경하세요
  - host: tr-[82061375].ce-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-82061375
            port:
              number: 8080
        pathType: Prefix
